version: '3.8'

services:

  wud-nest:
    container_name: nest-api-server
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - default

  mongodb:
    image: mongo
    container_name: MongoDB
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_DATABASE}
      - MONGO_USER=${MONGO_DB_USER}
      - MONGO_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - ${MONGO_DB_PORT}:27017
    networks:
      - default

  mongodb-express:
    image: mongo-express
    container_name: MongoDB-Webinterface
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_DB_ROOT_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_DB_ROOT_PASSWORD}
    networks:
      - default